language: perl
sudo: false
before_install:
    - npm install -g dredd
    - bundle install
script:
    - perl Build.PL && ./Build test
    - bundle exec cucumber
perl:
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
